name 'install_middleman'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures install_middleman'
long_description 'Installs/Configures install_middleman'
version '0.1.0'
